---
title: The Pulse of Night City
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: A Blog for our Cyberpunk campaign
baseurl: "/cyber-punk-blog"
url: ''
twitter_username: jekyllrb
github_username: jekyll
future: true